name: Deploy to Ninja Homepage

on:
  push:
    branches:
      - main  # mainブランチにpushされたときに実行

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install D2
      run: |
          curl -fsSL https://d2lang.com/install.sh | sh -s -- \
          export PATH=$HOME/.local/bin:$PATH

    - name: Install dependencies
      run: npm install --force

    - name: Build the project
      run: npm run build

    - name: Deploy to Ninja Homepage
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER_NINJA }}
        username: ${{ secrets.FTP_USERNAME_NINJA }}
        password: ${{ secrets.FTP_PASSWORD_NINJA }}
        local-dir: ./dist/
        server-dir: / 

    - name: Update sitemap 
      run: |
         curl -X GET "http://www.google.com/ping?sitemap=https://mathdoc.ifdef.jp/sitemap-0.xml"

    - name: IndexNow 
      uses: bojieyang/indexnow-action@v2 # v2 is the latest major version following the action-versioning.
      with:
      # The location of your sitemap must start with http(s). 
      # Currently, XML Sitemap, Sitemap index, RSS and Atom formats are supported.
        sitemap-location: 'https://mathdoc.ifdef.jp/sitemap-0.xml' 
        key: ${{ secrets.INDEXNOW_KEY }} # The key you get from IndexNow. 