name: Deploy to Ninja Homepage

on:
  push:
    branches:
      - main  # mainブランチにpushされたときに実行

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install --force

    - name: Build the project
      run: npm run build

    - name: Deploy to Ninja Homepage
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER_NINJA }}
        username: ${{ secrets.FTP_USERNAME_NINJA }}
        password: ${{ secrets.FTP_PASSWORD_NINJA }}
        local-dir: ./dist/
        server-dir: / 